# Robinhood Trading System Configuration
# Last updated: January 2025
# IMPORTANT: Update these settings before running live!

# API Configuration
data_sources:
  yahoo_finance:
    enabled: true
    rate_limit: 2000  # requests per hour
    cache_ttl: 300    # 5 minutes cache
  
  alpha_vantage:
    enabled: false
    api_key: "YOUR_ALPHA_VANTAGE_KEY_HERE"
    rate_limit: 500   # daily limit for free tier
    premium: false

# Account Configuration  
account:
  initial_balance: 10000        # Starting account balance
  monthly_budget: 1000          # Monthly trading budget
  max_position_size_pct: 10     # Max 10% per position
  reserve_cash_pct: 20          # Keep 20% cash reserve
  minimum_trade_size: 100       # Minimum $100 per trade

# Risk Management Parameters
risk:
  # Position Risk
  max_portfolio_risk_pct: 6     # Max 6% total portfolio risk
  max_position_risk_pct: 2      # Max 2% risk per position
  max_daily_loss: 100           # Stop trading if down $100/day
  max_consecutive_losses: 3     # Suspend after 3 losses in a row
  
  # Stop Loss & Targets
  default_stop_loss_pct: 5      # 5% default stop loss
  default_take_profit_pct: 10   # 10% default profit target
  trailing_stop_enabled: true   # Enable trailing stops
  trailing_stop_pct: 3          # 3% trailing stop
  
  # Concentration Limits
  max_single_stock_pct: 15      # Max 15% in one stock
  max_sector_pct: 30            # Max 30% in one sector
  max_correlation: 0.7          # Max correlation between positions

# Pattern Day Trading (PDT) Rules
pdt:
  account_minimum: 25000        # PDT minimum account size
  day_trade_limit: 3            # Max day trades per 5 days (non-PDT)
  day_trade_reset_days: 5       # Days for day trade limit reset
  
# Alert & Notification Settings
notifications:
  discord:
    enabled: false
    webhook_url: "YOUR_DISCORD_WEBHOOK_URL"
    alert_levels: ["signal", "entry", "exit", "risk"]
  
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    sender_email: "your_email@gmail.com"
    sender_password: "your_app_specific_password"
    recipient_email: "your_email@gmail.com"
    alert_levels: ["risk", "daily_summary"]

# Scanner Configuration
scanners:
  # Scheduling
  run_times:
    - "09:15"  # Pre-market scan
    - "09:35"  # Post-opening scan  
    - "10:00"  # Morning momentum scan
    - "14:00"  # Afternoon opportunity scan
    - "15:30"  # End of day scan
  
  # Universe Selection
  universe:
    min_price: 5.00             # Minimum stock price
    max_price: 1000.00          # Maximum stock price  
    min_volume: 500000          # Minimum average daily volume
    min_market_cap: 100000000   # $100M minimum market cap
    exchanges: ["NYSE", "NASDAQ"]
    exclude_sectors: ["REITs"]   # Sectors to exclude
    
  # Technical Filters
  technical_filters:
    min_rsi: 30                 # Minimum RSI for mean reversion
    max_rsi: 80                 # Maximum RSI to avoid overbought
    min_volume_ratio: 1.2       # Min volume vs average (20% above)
    max_gap_pct: 15             # Max gap up/down percentage
    
# Strategy Parameters
strategies:
  momentum:
    enabled: true
    # Signal Criteria
    min_signal_strength: 65     # Minimum signal strength to trade
    rsi_range: [50, 80]         # RSI range for momentum
    volume_multiplier: 1.5      # Volume must be 1.5x average
    price_change_min: 2.0       # Minimum 2% price move
    
    # Entry/Exit Rules
    entry_delay_minutes: 5      # Wait 5 min after signal
    max_holding_days: 30        # Maximum holding period
    profit_taking_levels: [5, 10, 15]  # Take profits at these %
    
    # Risk Parameters
    max_positions: 10           # Max simultaneous momentum positions
    position_correlation_limit: 0.6
    
  mean_reversion:
    enabled: true
    # Signal Criteria  
    min_signal_strength: 60
    rsi_oversold: 30            # RSI level for oversold
    zscore_threshold: -2.0      # Z-score for mean reversion
    bollinger_position: 0.1     # Below lower Bollinger Band
    
    # Entry/Exit Rules
    entry_delay_minutes: 10     # More conservative entry
    max_holding_days: 14        # Shorter holding for mean reversion
    profit_target_pct: 8        # Target 8% profit
    
    # Risk Parameters  
    max_positions: 8            # Fewer mean reversion positions
    
  volatility_breakout:
    enabled: true
    # Signal Criteria
    min_signal_strength: 70
    atr_multiplier: 2.5         # Breakout above 2.5x ATR
    consolidation_days: 10      # Look for 10-day consolidation
    volume_surge: 2.0           # 2x volume surge required
    
    # Risk Parameters
    max_positions: 5            # Conservative position count
    
  crypto_momentum:
    enabled: false              # Disabled by default
    symbols: ["BTC-USD", "ETH-USD", "BNB-USD"]
    min_signal_strength: 75
    max_positions: 3

# Backtesting Parameters
backtesting:
  # Data Requirements
  min_history_days: 252        # 1 year minimum for backtesting
  warm_up_days: 50             # Warm-up period for indicators
  
  # Validation Settings  
  walk_forward:
    in_sample_days: 252        # 1 year optimization period
    out_sample_days: 63        # 3 month testing period
    min_trades: 30             # Minimum trades for valid test
    
  monte_carlo:
    simulations: 1000          # Number of MC simulations
    confidence_level: 95       # Confidence level for results
    
  # Performance Criteria
  min_sharpe_ratio: 1.0        # Minimum acceptable Sharpe
  min_win_rate: 45             # Minimum 45% win rate
  max_drawdown: 20             # Maximum 20% drawdown
  min_profit_factor: 1.3       # Minimum profit factor

# Performance Tracking
performance:
  benchmark: "SPY"              # Compare performance against S&P 500
  risk_free_rate: 0.05          # For Sharpe ratio calculation
  
# Paper Trading Mode (for testing)
paper_trading:
  enabled: true               # Start in paper trading mode
  initial_balance: 10000
  commission_per_trade: 0.00  # No commission for paper trading
  realistic_slippage: 0.05    # 0.05% slippage simulation
  
# Live Trading (disable until ready)
live_trading:
  enabled: false              # Disabled by default - SAFETY FIRST!
  broker: "robinhood"
  max_daily_trades: 20        # Safety limit
  confirm_orders: true        # Require confirmation for live orders